# Generated by Django 5.1.7 on 2025-06-03 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=20, verbose_name='Уровень')),
                ('instructor', models.CharField(max_length=100, verbose_name='Инструктор')),
                ('schedule', models.CharField(max_length=100, verbose_name='Расписание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('max_students', models.IntegerField(verbose_name='Максимальное количество студентов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Танцевальный класс',
                'verbose_name_plural': 'Танцевальные классы',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('dance_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_site.danceclass', verbose_name='Танцевальный класс')),
            ],
            options={
                'verbose_name': 'Запись на класс',
                'verbose_name_plural': 'Записи на классы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dance_classes', models.ManyToManyField(through='test_site.Enrollment', to='test_site.danceclass', verbose_name='Танцевальные классы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_site.student', verbose_name='Студент'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'dance_class')},
        ),
    ]
